### ISSUE TITLE
Add Travis tests for clang

### ISSUE THREAD

**Issue by certik** [sympy/csympy#142]
Here is how to compile with clang 3.4 on Ubuntu:
```
CXX=clang cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_CSYMPY_ASSERT=yes -DWITH_BFD=yes -DLIBS="stdc++ -lm" .
```
Notice the extra `-DLIBS="stdc++ -lm"` argument. Without it the linking fails. It'd be nice to figure out why this is needed. But more importantly, add a simple test to Travis, just to make sure it compiles with clang.

**Comment by isuruf** [comment]
Closed via #354
