### ISSUE TITLE
Add an EyeMatrix class and DiagMatrix class

### ISSUE THREAD

**Issue by thilinarmtb** [sympy/csympy#275]
As suggested by @thisch [here](https://github.com/sympy/csympy/pull/256/files#r16010013), it would be nice to have convenient methods to create identity matrices and diagonal matrices directly.

**Comment by shivamvats** [comment]
This seems to have been fixed by PR #332 . Should be closed.

**Comment by thilinarmtb** [comment]
Yes, this was fixed by #332. Thanks @shivamvats for noticing this.
