### ISSUE TITLE
Tests depend on compiler implementation

### ISSUE THREAD

**Issue by isuruf** [sympy/csympy#355]
Tests like `assert(r2->__str__() == "(y + x)^(2/3)*x" );` depends on the hash value of `x + y` and `x`. `std::hash` returns a `size_t` object and it is compared when ordering `x + y` and `x`, but std::hash is compiler dependent.

**Comment by certik** [comment]
Indeed. The solution is to fix #377 first and then update the tests using the new printer.

**Comment by isuruf** [comment]
Fixed in #423
