### ISSUE TITLE
ImportError: No module named 'csympy.compatibility'

### ISSUE THREAD

**Issue by benruijl** [sympy/csympy#390]
This is what I get when I type `import csympy' in Python 3.4:

Traceback (most recent call last):
  File "pathforcer.py", line 14, in <module>
    from csympy import Symbol, symbols, solve, Add
  File "/usr/lib/python3.4/site-packages/csympy/__init__.py", line 3, in <module>
    from .utilities import var, symbols
  File "/usr/lib/python3.4/site-packages/csympy/utilities.py", line 2, in <module>
    from .compatibility import string_types
ImportError: No module named 'csympy.compatibility'

**Comment by isuruf** [comment]
#391 should fix this

**Comment by certik** [comment]
Thanks for the report @benruijl ---- we thought we are testing for this on Travis, but as it turns out, we only tested if you install using `setup.py`, which apparently does not call `make install` (which had the bug). So we are improving our tests now.

**Comment by certik** [comment]
@pbrady you might be interested in this. It would be cool if we could somehow figure out how to force `setup.py` to call our `make install`, as that would greatly simplify our tests and setup. Currently we have to test `setup.py install` separately from `make install` for Python.

**Comment by pbrady** [comment]
I don't think there's any reason why we can't.  It's likely just a matter of making of processing setup.py flags and translating them into something reasonable that cmake/make understand.
