### ISSUE TITLE
Power should be printed as **, not ^

### ISSUE THREAD

**Issue by jmmcd** [sympy/csympy#403]
I think the goal is to get the same results as sympy, only faster. In that case:

```
>>> import sympy
>>> sympy.var("x")
>>> 2**x
2**x
```

Whereas:

```
>>> import csympy
>>> csympy.var("x")
>>> 2**x
2^x
```

See https://github.com/sympy/csympy/blob/master/src/pow.cpp#L108

**Comment by certik** [comment]
Thanks for the report @jmmcd, yes that should be fixed. Ultimately we should add multiple printers using our single dispatch, to mirror SymPy's printers.

**Comment by asmeurer** [comment]
Or maybe just use SymPy's printers, since I doubt printing will be a bottleneck for most operations (as long as you are careful not to call str for internal operations).

**Comment by Sumith1896** [comment]
@certik The above PR should fix this issue.

**Comment by certik** [comment]
@asmeurer printing is actually a large bottleneck for bigger expressions. We should put up some benchmarks for that.

**Comment by jmmcd** [comment]
Thanks all, and thanks for making csympy!

**Comment by certik** [comment]
Thanks for trying it @jmmcd. If you find more problems, please report them.
